# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
name: AudioQnA-deployment

services:
  whisper-service:
    image: ${REGISTRY:-opea}/whisper:${TAG:-latest}
    container_name: whisper-service
    ports:
      - ${WHISPER_SERVER_PORT:-7066}:7066
    ipc: host
    volumes:
      - whisper-data:/home/user/.cache/whisper
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    restart: unless-stopped
    command: --model_name_or_path openai/whisper-tiny    
  speecht5-service:
    image: ${REGISTRY:-opea}/speecht5:${TAG:-latest}
    container_name: speecht5-service
    ports:
      - ${SPEECHT5_SERVER_PORT:-7055}:7055
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    restart: unless-stopped
  llm-ollama-service:
    extends: 
      file: ../../../comps/third_parties/ollama/deployment/docker_compose/compose.yaml
      service: ollama-server
    container_name: llm-ollama-server
    volumes:
      - ollama-data:/root/.ollama
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      CUDA_VISIBLE_DEVICES: 0
      LOG_LEVEL: debug
      LLM_COMPONENT_NAME: ${LLM_COMPONENT_NAME:-OpeaTextGenService}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    tty: true
    # networks:
    #   ${NETW_NAME:-opea-network}:
    #     ipv4_address: ${LLM_HOST_IP:-10.5.0.2}
    extra_hosts:
      - "host.docker.internal:host-gateway"                
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://${LLM_HOST_IP}:${LLM_SERVER_PORT}/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 100
  audioqna-xeon-backend-server:
    image: ${REGISTRY:-opea}/audioqna:${TAG:-latest}
    container_name: audioqna-xeon-backend-server
    depends_on:
      - whisper-service
      - llm-ollama-service
      - speecht5-service
    ports:
      - "3008:8888"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${MEGA_SERVICE_HOST_IP}
      - WHISPER_SERVER_HOST_IP=${WHISPER_SERVER_HOST_IP}
      - WHISPER_SERVER_PORT=${WHISPER_SERVER_PORT}
      - LLM_SERVER_HOST_IP=${LLM_SERVER_HOST_IP}
      - LLM_SERVER_PORT=${LLM_SERVER_PORT}
      - LLM_MODEL_ID=${LLM_MODEL_ID}
      - SPEECHT5_SERVER_HOST_IP=${SPEECHT5_SERVER_HOST_IP}
      - SPEECHT5_SERVER_PORT=${SPEECHT5_SERVER_PORT}
    ipc: host
    restart: always
  audioqna-xeon-ui-server:
    image: ${REGISTRY:-opea}/audioqna-ui:${TAG:-latest}
    container_name: audioqna-xeon-ui-server
    depends_on:
      - audioqna-xeon-backend-server
    ports:
      - "5173:5173"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - CHAT_URL=${BACKEND_SERVICE_ENDPOINT}
    ipc: host
    restart: always


# Delete this if you want the volume to be internal
volumes:
  ollama-data: 
    external: true
  whisper-data: 
    external: true    

networks:
  ${NETW_NAME:-default}:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: ${OPEA_NETW_SUBNET:-10.5.0.0/16}
    #       gateway: ${OPEA_NETW_GATEWAY:-10.5.0.1}
