version: '3'

services:
  python-api:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bookworm
    volumes:
      - ..:/workspaces/free-genai-bootcamp-2025:cached
    command: sleep infinity
    networks:
      - genai-network

  node-frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ..:/workspaces/free-genai-bootcamp-2025:cached
    command: sleep infinity
    networks:
      - genai-network

networks:
  genai-network:
    name: genai-network