version: '3'

services:
  ollama-server:
    image: ollama/ollama
    container_name: llm-ollama-server2
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - ${LLM_ENDPOINT_PORT:-8008}:11434
    runtime: nvidia
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      host_ip: ${host_ip}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      CUDA_VISIBLE_DEVICES: 0
      LOG_LEVEL: debug
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    tty: true
    networks:
      - ollama-net      
    restart: unless-stopped

  python-opea-api:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bookworm
    volumes:
      - ..:/workspaces/free-genai-bootcamp-2025:cached
    command: sleep infinity
    networks:
      - ollama-net     

volumes:
  ollama-data: 
    external: true
    
networks:
  ollama-net:
    driver: bridge