# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - ${LLM_ENDPOINT_PORT:-8008}:11434
    runtime: nvidia
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      host_ip: ${host_ip}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      CUDA_VISIBLE_DEVICES: 0
      LOG_LEVEL: debug
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    tty: true
    networks:
      - ollama-net    
    restart: unless-stopped

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - MODEL_DOWNLOAD_DIR=/models
      - OLLAMA_API_BASE_URL=http://ollama-server:11434
      - OLLAMA_API_URL=http://ollama-server:11434
      - LOG_LEVEL=debug
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 3000:8080
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    depends_on:
      - ollama-server
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    networks:
      - ollama-net
    restart: unless-stopped

volumes:
  open-webui:
    external: true
  ollama-data: 
    external: true

networks:
  ollama-net:
    driver: bridge