# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  ollama-server:
    extends: 
      file: ../../../comps/third_parties/ollama/deployment/docker_compose/compose.yaml
      service: ollama-server
    container_name: ollama-server
    volumes:
      - ollama-data:/root/.ollama
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      CUDA_VISIBLE_DEVICES: 0
      LOG_LEVEL: debug
      LLM_COMPONENT_NAME: ${LLM_COMPONENT_NAME:-OpeaTextGenService}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    tty: true
    networks:
      ollama-net:
        ipv4_address: ${LLM_HOST_IP:-10.5.0.2} 
    extra_hosts:
      - "host.docker.internal:host-gateway"                
    restart: unless-stopped

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - MODEL_DOWNLOAD_DIR=/models
      - OLLAMA_API_BASE_URL=${LLM_ENDPOINT}
      - OLLAMA_API_URL=${LLM_ENDPOINT}
      - LOG_LEVEL=debug
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${WEBUI_PORT_HOST:-3000}:${WEBUI_PORT_CONTAINER:8080}
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    depends_on:
      - ollama-server
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    networks:
      ollama-net:
        ipv4_address: ${WEBUI_HOST_IP:-10.5.0.3} 
    restart: unless-stopped

volumes:
  open-webui:
    external: true
  ollama-data: 
    external: true

networks:
  ollama-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${OLLAMA_NETW_SUBNET:-10.5.0.0/16}
          gateway: ${OLLAMA_NETW_GATEWAY:-10.5.0.1}